### ISSUE TITLE
Add interested button in each button

### ISSUE THREAD

**Issue by ExpressHermes** [ExpressHermes/Helping-Hand#12]
Add a 'interested' button to the event model and maintain a count of people who have clicked this button.

**Comment by subhangi2731** [comment]
can you assign me this @ExpressHermes

**Comment by ExpressHermes** [comment]
Done @subhangi2731!

**Comment by Praneeth-rdy** [comment]
Should we keep track of only the **count of users** or the **users** who clicked the button?
