### ISSUE TITLE
Add email confirmation feature to avoid spams

### ISSUE THREAD

**Issue by ExpressHermes** [ExpressHermes/Helping-Hand#14]

**Comment by subhangi2731** [comment]
can you assign me this @ExpressHermes

**Comment by ExpressHermes** [comment]
sure @subhangi2731

**Comment by praneeth-rdy** [comment]
Maybe we'll need a temporary Gmail-ID with third-party privacy setting allowed to implement this.
If anyone already created one, then share its credentials here if possible.

**Comment by ExpressHermes** [comment]
@Praneeth-rdy you can use your own gmail id temporarily, the privacy feature is disabled by google automatically after a fixed amount of time so it's not an issue.

**Comment by pulkitchauhan03** [comment]
Can u assign me this @ExpressHermes  ??

**Comment by ExpressHermes** [comment]
@pulkitchauhan03 assignment is not necessary for contribution. Make a PR for this and I will be glad to review and merge that.

**Comment by pulkitchauhan03** [comment]
Cool

**Comment by Subhankar4901** [comment]
@ExpressHermes By email confirmation you mean verify the user is legit ??

**Comment by pulkitchauhan03** [comment]
I've done it. I will make a pull request tommorow

**Comment by Subhankar4901** [comment]
ohhh cool. 😊

**Comment by ExpressHermes** [comment]
> @ExpressHermes By email confirmation you mean verify the user is legit ??

Yes, like sending email to the user with profile activation link or sending OTP to email and asking for it just after sign up

**Comment by ExpressHermes** [comment]
Fixed in #25
