### ISSUE TITLE
Update requirements and add configs for google authentication

### ISSUE THREAD

**Issue by ritikalohia** [ExpressHermes/Helping-Hand#28]
I have gone through the project and get an issue. There are some requirements missing in requirements.txt and added credentials, that were added in the admin side to the code. updates in settings and requirements.txt

**Comment by ritikalohia** [comment]
so, can I pull request the updates? @ExpressHermes

**Comment by ExpressHermes** [comment]
Sure. try to make sure this time all the requirements are there in `requirements.txt`

**Comment by ritikalohia** [comment]
ok, thanks
